# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FamilyTree' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FamilyTree
  pod 'ARSLineProgress', '~> 2.0'
  pod 'SwiftyJSON'
  pod 'ObjectMapper', '~> 2.2'
  pod 'Siesta', '~> 1.0'
  pod 'Siesta/UI', '~> 1.0'
  pod 'Siesta/Alamofire', '~> 1.0'
  pod 'Toaster', '~> 2.0'
  pod 'IQKeyboardManager'
  pod 'SwiftyUserDefaults'
  pod 'Former'
  pod 'SwiftDate', '~> 4.0'
  pod 'Swinject'
  pod 'SwinjectPropertyLoader'
  pod 'SwinjectStoryboard'
  pod 'SwinjectAutoregistration'
  pod 'RealmSwift'
  pod 'EasyRealm', '~> 1.1.0'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
